### ISSUE TITLE
Remote display with MQTT support?

### ISSUE THREAD

**Issue by ecsfang** [petli/codplayer#40]
Hi Peter,

Might be off topic - but how about MQTT support?
I have setup codplayer on my HTPC and I also fixed so I can cast audio to other speakers/amplifiers in my house. To handle the playing I can of course use the web-page which works fine.
But, I was thinking of adding a small display, similar to yours, but make it remote, e.g. a small display added to an wifi enabled device (arduino/esp8266). If this could talk MQTT (sending play-/next-commands etc), and codplayer could respond with updated text to the display it would be cool :)

I have not yet looked so much at the code yet, but I guess that I could implement my own LCD-class, and add the support there. Any suggestions or thoughts?

Cheers,
Thomas

**Comment by petli** [comment]
Hi,

codplayer is already controlled through ZeroMQ, not quite the same as MQTT but for your purposes I think it could work just as well?   As long as you can do TCP, there ought to be an ZeroMQ library as well for the platform.  If not, it would be straightforward to build a small MQTT-ZeroMQ proxy.

The endpoints are defined in codmq.conf, and if you're coding the clients in Python there are also helper classes for the communication - look at what codctl is doing, e.g.

The ZeroMQ endpoints and protocol is documented here:
https://github.com/petli/codplayer/blob/master/doc/zeromq.md

**Comment by ecsfang** [comment]
Oh, great! Missed that, and that should be no problem. 
Thanks for the tip, I'll start looking at ZeroMQ then 😊
Cheers!

**Comment by petli** [comment]
I'm curious what you'll build, so ping me when you have something to show. :)
